# CSCI 513.01W – Python Programming for AI
## Assignment 4 - NumPy

## Exercise I

Create an array called prices of 50 random float numbers between 0 and 100 (inclusive).

In [2]:
import numpy as np

np.random.seed(42)
prices = np.random.random(50) * 100

print(prices)
print(prices.shape)


[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404 15.59945203
  5.80836122 86.61761458 60.11150117 70.80725778  2.05844943 96.99098522
 83.24426408 21.23391107 18.18249672 18.34045099 30.4242243  52.47564316
 43.19450186 29.12291402 61.18528947 13.94938607 29.21446485 36.63618433
 45.60699842 78.51759614 19.96737822 51.42344384 59.24145689  4.64504127
 60.75448519 17.05241237  6.5051593  94.88855373 96.56320331 80.83973481
 30.46137692  9.7672114  68.42330265 44.01524937 12.20382348 49.51769101
  3.43885211 90.93204021 25.87799816 66.25222844 31.17110761 52.00680212
 54.67102793 18.48544555]
(50,)


## Exercise II
- Create a NumPy array called ages. This array should have 15 random ages between 5 and 25 (inclusive)
- Create a NumPy array called ages2. The values in ages2 should be double the ones in ages.

In [3]:
ages = np.random.randint(5, 26, size=15)
ages2 = ages * 2

print(ages)
print(ages2)

[22 16  6 14  8 18 20 19 12 18 12 25 20 17 22]
[44 32 12 28 16 36 40 38 24 36 24 50 40 34 44]


## Exercise III

To make ages2 a little bit more realistic, insert a little random noise into each element of the array you created. To be more precise, modify each value assigned to ages2 by adding a different random floating-point value between -2 and +2.

In [4]:
noise =  np.random.randint(-2, 3, size=15)
ages2 = ages2 + noise

print(noise)
print(ages2)

[ 2 -1 -2  1  1  1  2 -2  2  2 -2 -2 -2 -2  1]
[46 31 10 29 17 37 42 36 26 38 22 48 38 32 45]


# Exercise IV
Suppose we have two numpy arrays that represent the price of the same items from different stores:

store1 = np.array([29, 4, 2, 30, 15, 48, 63, 32, 53, 70, 47, 19, 24])
store2 = np.array([23, 2, 12, 32, 25, 47, 53, 39, 63, 71, 47, 18, 21])

Create a new array where we take the value from store1 whenever the corresponding value in cond is True, otherwise we take the value from store2.

cond = np.array([False, True, False, False, False, True, False, False, True, True, False, False, True])

In [19]:
store1 = np.array([29, 4, 2, 30, 15, 48, 63, 32, 53, 70, 47, 19, 24])
store2 = np.array([23, 2, 12, 32, 25, 47, 53, 39, 63, 71, 47, 18, 21])

cond = np.array([False, True, False, False, False, True, False, False, True, True, False, False, True])

price_result = np.empty(store1.shape)

for index in np.arange(0, cond.shape[0]):
    if cond[index]:
        price_result[index] = store1[index]
    else:
        price_result[index] = store2[index]

print(price_result)

[23.  4. 12. 32. 25. 48. 53. 39. 53. 70. 47. 18. 24.]


# Exercise V

Solve Exercise IV using numpy where function.

In [18]:
price_result = np.where(cond, store1, store2)
print(price_result)

[23  4 12 32 25 48 53 39 53 70 47 18 24]


# Exercise VI

Suppose we have the scores from players playing an arcade game:

scores = np.random.randint(low=0, high=70, size=[2000])

1. Retrieve the scores that are greater than 20.
2. Retrieve the scores that are not 30.
3. Retrieve the average score.
4. Retrieve the minimum score.
5. Retrieve the maximum score.

In [21]:
scores = np.random.randint(low=0, high=70, size=[2000])

greater_20 = scores[scores > 20]
not_30 = scores[scores != 30]
average = scores.mean()
minimum = scores.min()
maximum = scores.max()

print(average)
print(greater_20)
print(not_30)
print(minimum)
print(maximum)

35.2395
[28 51 26 ... 32 56 51]
[28 51 26 ... 56 51  8]
0
69
